<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lecturer</name>
   <tag></tag>
   <elementGuidId>433dd1b5-8380-413c-88a4-91ba8de5afb9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lecturer-crud</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lecturer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-student-crud[1]/body[@class=&quot;grey lighten-4&quot;]/nav[@class=&quot;blue darken-2&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;nav-wrapper&quot;]/ul[@class=&quot;right hide-on-med-and-down&quot;]/li[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
